import SiteFooter from './_components/site/SiteFooter';
import SiteHeader from './_components/site/SiteHeader';
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import { Providers } from './providers';
import { SessionProvider } from 'next-auth/react';

export const metadata = {
  title: 'Event Manager',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark'>
      <head>
      </head>
      <body>
        <Providers>
          <SessionProvider>
            <SiteHeader />
            {children}
            <SiteFooter />
          </SessionProvider>
        </Providers>
      </body>
    </html>
  )
}
