import SiteFooter from './_components/SiteFooter';
import SiteHeader from './_components/SiteHeader';
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import { Providers } from './providers';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark'>
      <head>
      </head>
      <body>
        <Providers>
          <SiteHeader />
          {children}
          <SiteFooter />
        </Providers>
      </body>
    </html>
  )
}
